Repository rustsec/advisory-db, pull requests merged in 2022-09, with the labels that each got.

#1400 Add unmaintained `wee_alloc`
  crates/wee_alloc/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#1390 Add unmaintained `traitobject`
  crates/traitobject/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1417 Add `axum-core` DoS
  crates/axum-core/RUSTSEC-0000-0000.md
Labels: denial of service

#1420 Fix informational footnote wording
  README.md
Labels: Documentation

#1267 Add unmaintained `clipboard`
  crates/clipboard/RUSTSEC-0000-0000.md
Labels: Unmaintained
