Repository rustsec/advisory-db, pull requests merged in 2022-08, with the labels that each got.

#1275 Add unmaintained advisory for term_size
  crates/term_size/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1150 Add unmaintained advisory for r2d2-odbc
  crates/r2d2-odbc/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1151 Add unmaintained advisory for odbc
  crates/odbc/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1228 sass-rs is deprecated
  crates/sass-rs/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1188 Initial advisory for owning_ref unsoundness
  crates/owning_ref/RUSTSEC-0000-0000.md
Labels: Unsound

#1304 Add Crossbeam AtomicCell<*64> Soundness #1203
  crates/crossbeam-utils/RUSTSEC-0000-0000.md
Labels: Unsound

#1191 List `markdown` as unmaintained
  crates/markdown/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1237 Add out-of-bounds read advisory for rocksdb
  crates/rocksdb/RUSTSEC-0000-0000.md
Labels: memory corruption, Waiting-Author, Waiting-Maintainer, Propose-Merge

#1144 Added informal advisory to mz-avro
  crates/mz-avro/RUSTSEC-0000-0000.md
Labels: Unsound, Waiting-Author

#1356 Add unmaintained ` xml-rs`
  crates/xml-rs/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1364 Remove `yanked` 2
  .github/workflows/validate.yml
  crates/directories/RUSTSEC-2020-0054.md
  crates/dirs/RUSTSEC-2020-0053.md
  crates/libpulse-binding/RUSTSEC-2020-0055.md
  crates/spin/RUSTSEC-2019-0031.md
  crates/tower-http/RUSTSEC-2021-0135.md
Labels: Blocker-Tooling

#1355 Document `withdrawn`
  README.md
Labels: Documentation

#1366 iana-time-zone v0.1.{43,44}: Use after free in MacOS / iOS implementation
  crates/iana-time-zone/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1370 Document empty `versions` field use
  README.md
Labels: Documentation

#1369 Add unmaintained `interledger`
  crates/interledger-packet/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#1372 Add unmaintained `ansi_term`
  crates/ansi_term/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#1381 Remove mapr as alternativ from RUSTSEC-2020-0077
  crates/memmap/RUSTSEC-2020-0077.md
Labels: Feedback

#1382 Add unmaintained `mapr`
  crates/mapr/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1391 add advisory for cell-project
  crates/cell-project/RUSTSEC-0000-0000.md
Labels: Unsound, Propose-Merge

#1388 Add unmaintained `rusttype`
  crates/rusttype/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#1359 Add unmaintained `dotenv` & Co.
  crates/dotenv/RUSTSEC-0000-0000.md
  crates/dotenv_codegen/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge
