Repository rustsec/advisory-db, pull requests merged in 2023-03, with the labels that each got.

#1624 Add unmaintained advisory for nphysics
  crates/nphysics2d/RUSTSEC-0000-0000.md
  crates/nphysics3d/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1623 Add unmaintained advisory for ncollide
  crates/ncollide2d/RUSTSEC-0000-0000.md
  crates/ncollide3d/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1627 `out_reference::Out::from_raw` should be `unsafe`
  crates/out-reference/RUSTSEC-0000-0000.md
Labels: Unsound, Propose-Merge

#1616 Add unmaintained advisory for mach
  crates/mach/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#1613 Add unsound `const-cstr`
  crates/const-cstr/RUSTSEC-0000-0000.md
Labels: Unmaintained, Unsound, Propose-Merge

#1650 Add unsound `rmp-serde`
  crates/rmp-serde/RUSTSEC-0000-0000.md
Labels: Unsound

#1614 Add unmaintained `buf_redux`
  crates/buf_redux/RUSTSEC-0000-0000.md
Labels: Unmaintained
