Repository rustsec/advisory-db, pull requests merged in 2023-01, with the labels that each got.

#1510 Add `tokio` CVE-2023-22466
  crates/tokio/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1509 Add `wasmtime` CVE-2022-39393
  crates/wasmtime/RUSTSEC-0000-0000.md
Labels: memory exposure, Propose-Merge

#1513 Update RUSTSEC-2021-0086.md
  crates/flumedb/RUSTSEC-2021-0086.md
Labels: Waiting-Author

#1521 Report claim as unmaintained.
  crates/claim/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1450 Add advisory for elf_rs crate
  crates/elf_rs/RUSTSEC-0000-0000.md
Labels: memory corruption, Unsound, Waiting-Maintainer, Feedback

#1435 Add unmaintained `twoway`
  crates/twoway/RUSTSEC-0000-0000.md
Labels: Unmaintained, Waiting-Maintainer

#1528 Add parity-util-mem unmaintained
  crates/parity-util-mem/RUSTSEC-0000-0000.md
Labels: Unmaintained

#1536 Report json as unmaintained
  crates/json/RUSTSEC-0000-0000.md
Labels: Unmaintained
