Repository rustsec/advisory-db, pull requests merged in 2023-02, with the labels that each got.

#1549 Add `personnummer`
  crates/personnummer/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1551 Add `evm`
  crates/evm/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1555 Add `libp2p` DoS
  crates/libp2p/RUSTSEC-0000-0000.md
Labels: denial of service, Propose-Merge

#1550 Add `matrix-sdk-crypto`
  crates/matrix-sdk-crypto/RUSTSEC-0000-0000.md
Labels: cryptographic failure, Propose-Merge

#1556 Add `slack-morphism` CVE-2022-31162
  crates/slack-morphism/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1557 Add `slack-morphism` CVE-2022-39292
  crates/slack-morphism/RUSTSEC-0000-0000.md
Labels: Propose-Merge

#1554 Add `bzip2` DoS
  crates/bzip2/RUSTSEC-0000-0000.md
Labels: denial of service, Propose-Merge

#1552 Add tokio `io::ReadHalf<T>::unsplit` unsound
  crates/tokio/RUSTSEC-0000-0000.md
Labels: Unsound, Propose-Merge

#1571 Add advisory Tauri filesystem scope bypass
  crates/tauri/RUSTSEC-0000-0000.md
Labels: Propose-Merge
