Repository rustsec/advisory-db, pull requests merged in 2024-12, with the labels that each got.

#2100 Add disclosure for hasbrown's borsh encoding
  crates/hashbrown/RUSTSEC-0000-0000.md
Labels: Waiting-Author

#1553 Add unmaintained `multi_mut`
  crates/multi_mut/RUSTSEC-0000-0000.md
Labels: Unmaintained, Propose-Merge

#2103 report serial crates as unmaintained
  crates/serial/RUSTSEC-0000-0000.md
Labels: Waiting-Author

#2079 Add unmaintained advisories
  crates/get-size-derive/RUSTSEC-0000-0000.md
  crates/get-size/RUSTSEC-0000-0000.md
Labels: Waiting90d
